server:
  port: ${PORT:8080}

spring:
  application:
    name: personal-site       # 项目名
  thymeleaf:
    cache: false              # 开发时关闭模板缓存，改 html 立即生效
    prefix: classpath:/templates/
    suffix: .html

# 其他配置
logging:
  level:
    root: INFO